import { BarChart3, BookOpen, ChevronDown, Plus, Sparkles, Target, TrendingUp } from 'lucide-react'
import type { Trade } from '../types'
import { useMoney } from '../currency'

export default function ForexJournalPage({ trades, onAdd, notify }: { trades: Trade[]; onAdd: () => void; notify: (message: string) => void }) {
  const money = useMoney(); const wins = trades.filter((trade) => trade.result > 0).length; const net = trades.reduce((sum, trade) => sum + trade.result, 0)
  return <><div className="page-heading"><div><p className="eyebrow">Trading journal</p><h1>Trade with intention.</h1><p className="subheading">Track the setup, not just the outcome.</p></div><button className="primary-button" onClick={onAdd}><Plus size={18} /> Log a trade</button></div><div className="journal-stats"><Metric label="Win rate" value={trades.length ? `${Math.round(wins / trades.length * 100)}%` : '0%'} meta={`${wins} wins across ${trades.length} trades`} icon={<Target size={20} />} tone="mint" /><Metric label="Net P&L" value={money(net)} meta="From logged trades" icon={<TrendingUp size={20} />} tone="gold" /><Metric label="Average trade" value={trades.length ? money(net / trades.length) : money(0)} meta="Across the journal" icon={<BarChart3 size={20} />} tone="lavender" /><Metric label="Best pair" value={trades[0]?.pair || '—'} meta="Most recently logged" icon={<Sparkles size={20} />} tone="coral" /></div><section className="panel table-panel"><div className="panel-header"><div><span className="eyebrow">Recent entries</span><h2>Read your own tape</h2></div><button className="text-button" onClick={() => notify('Journal filters opened')}>Filter <ChevronDown size={14} /></button></div><div className="journal-list">{trades.map((trade) => <div className="journal-row" key={trade.id ?? `${trade.pair}-${trade.traded_on}`}><div className="pair-icon">{trade.pair.slice(0, 1)}</div><div><strong>{trade.pair}</strong><span>{trade.setup} · {trade.direction}</span></div><time>{trade.traded_on}</time><strong className={trade.result >= 0 ? 'positive' : 'negative'}>{money(trade.result)}</strong></div>)}</div>{!trades.length && <div className="empty-list"><BookOpen size={18} /> No trades logged yet.</div>}</section></>
}
function Metric({ label, value, meta, icon, tone }: { label: string; value: string; meta: string; icon: React.ReactNode; tone: string }) { return <div className="metric-card"><div className={`metric-icon ${tone}`}>{icon}</div><span className="metric-label">{label}</span><strong>{value}</strong><small>{meta}</small></div> }
